### ISSUE TITLE
Does RVIC include irrigation module and reservoir module?

### ISSUE THREAD

**Issue by zyl1027** [UW-Hydro/RVIC#105]
Dear sir, 
I read this paper "Effects of irrigation on the water and energy balances of the Colorado and Mekong river basins" and found that irrigation module and reservoir module have been added into the routing routine. Therefore, I want to ask, does RVIC include irrigation module and reservoir module?
Thanks!

**Comment by jhamman** [comment]
@zyl1027 - No, it doesn't. This sort of functionality would require a 3'rd party package for the irrigation and reservoir modeling.
