### ISSUE TITLE
[bug] subset_length must be a multiple of 2

### ISSUE THREAD

**Issue by kwhitney727** [UW-Hydro/RVIC#107]
lines 333, 334 of `param_file.py` in `subset` function define `d_left` and `d_right`, which need to be integers, to be +/-  `subset_length / 2`, which will be float if 'subset_length' is not a multiple of 2. Since `d_left` and `d_right` are used as array indices, they cannot have float values, yet there is no logic in rvic to ensure that `subset_length` is an even number.

**Comment by jhamman** [comment]
Thanks @kwhitney727 - this is a good point and I agree we should fix it. I'll take a look at your PR in a bit.

**Comment by jhamman** [comment]
closed via #109
