### ISSUE TITLE
run RVIC using sample rasm files throw unexpected errors

### ISSUE THREAD

**Issue by iacopoff** [UW-Hydro/RVIC#116]
Hi,
I have just installed RVIC on the linux server and I wanted to run the test cases that I have downloaded from RVIC/samples/.
I am wondering why, provided that the data inputs are fine, I am getting errors that seems more related to the code as you can see from the print of the log file below, but I may be wrong also in that... 

Could you tell where I am making some mistake?

many thanks

iacopo

INFO:init_logger>> -------------------- INITIALIZED RVIC LOG ------------------
INFO:init_logger>> LOG LEVEL: DEBUG
INFO:init_logger>> Logging To Console: True
INFO:init_logger>> LOG FILE: ./samples/cases/sample_rasm_parameters/logs/RVIC-20180912-123423.log
INFO:init_logger>> ----------------------------------------------------------

INFO:gen_uh_init>> plots directory is ./samples/cases/sample_rasm_parameters/plots
INFO:gen_uh_init>> logs directory is ./samples/cases/sample_rasm_parameters/logs
INFO:gen_uh_init>> params directory is ./samples/cases/sample_rasm_parameters/params
INFO:gen_uh_init>> inputs directory is ./samples/cases/sample_rasm_parameters/inputs
INFO:gen_uh_init>> aggregated directory is ./samples/cases/sample_rasm_parameters/temp/aggregated
INFO:gen_uh_init>> remapped directory is ./samples/cases/sample_rasm_parameters/temp/remapped
INFO:gen_uh_init>> Opened Pour Points File: ./samples/cases/sample_rasm_parameters/inputs/rasm_sample_pour_points.csv
INFO:gen_uh_init>> Opened UHbox File: ./samples/cases/sample_rasm_parameters/inputs/UH_RASM_hourly.csv
DEBUG:read_netcdf>> Reading input data variables: ['Basin_ID', 'Flow_Direction', 'Flow_Distance', 'Land_Mask', 'Source_Area', 'crs', 'lat', 'lon'], from file: ./samples/cases/sample_rasm_parameters/inputs/Wu_routing_inputs_060313.nc
DEBUG:gen_uh_init>> Flow Direction inputs came in upside down, flipping everything now.
DEBUG:gen_uh_init>> flipping Basin_ID
DEBUG:gen_uh_init>> flipping Flow_Direction
DEBUG:gen_uh_init>> flipping Flow_Distance
DEBUG:gen_uh_init>> flipping Land_Mask
DEBUG:gen_uh_init>> flipping Source_Area
DEBUG:gen_uh_init>> flipping crs
DEBUG:gen_uh_init>> flipping lat
DEBUG:gen_uh_init>> flipping lon
INFO:gen_uh_init>> Added velocity grid to fdr_data
INFO:gen_uh_init>> Added diffusion grid to fdr_data
INFO:gen_uh_init>> Opened FDR File: ./samples/cases/sample_rasm_parameters/inputs/Wu_routing_inputs_060313.nc
DEBUG:read_netcdf>> Reading input data variables: ['xc', 'yc', 'xv', 'yv', 'mask', 'area', 'frac'], from file: ./samples/cases/sample_rasm_parameters/inputs/domain.lnd.wr50a_ar9v4.100920.nc
INFO:gen_uh_init>> Opened Domain File: ./samples/cases/sample_rasm_parameters/inputs/domain.lnd.wr50a_ar9v4.100920.nc
INFO:make_agg_pairs>> Finding addresses now...
INFO:latlon2yx>> adjusted grid lon to astronomical conventions
INFO:make_agg_pairs>> 
------------------ SUMMARY OF MakeAggPairs ------------------
INFO:make_agg_pairs>> NUMBER OF POUR POINTS IN INPUT LIST: 10
INFO:make_agg_pairs>> NUMBER OF POINTS TO AGGREGATE TO: 5
INFO:make_agg_pairs>> NUMBER OF POUR POINTS AGGREGATED: 10
INFO:make_agg_pairs>> EFFECIENCY OF: 100.00 %
INFO:make_agg_pairs>> UNASSIGNED POUR POINTS: 0 

INFO:make_agg_pairs>> -------------------------------------------------------------

INFO:gen_uh_init>> Finished making agg pairs of pour points and outlet grid cells
DEBUG:gen_uh_init>> OrderedDict([(46050,     -- Point --    
name:	outlet_58.4107_93.4308
lat:	58.4107
lon:	93.4308
domy:	167
domx:	125
routy:	-9999
routx:	-9999
), (27396,     -- Point --    
name:	outlet_83.7711_-42.9300
lat:	83.7711
lon:	-42.9300
domy:	99
domx:	171
routy:	-9999
routx:	-9999
), (27673,     -- Point --    
name:	outlet_83.0264_-36.9934
lat:	83.0264
lon:	-36.9934
domy:	100
domx:	173
routy:	-9999
routx:	-9999
), (25467,     -- Point --    
name:	outlet_83.3996_-75.7979
lat:	83.3996
lon:	-75.7979
domy:	92
domx:	167
routy:	-9999
routx:	-9999
), (25468,     -- Point --    
name:	outlet_83.1114_-72.8403
lat:	83.1114
lon:	-72.8403
domy:	92
domx:	168
routy:	-9999
routx:	-9999
)])
INFO:gen_uh_init>> Finished with gen_uh_init
INFO:gen_uh_init>> -------------------------------------------------------------

INFO:gen_uh_run>> Running outlet cell id 46050
INFO:gen_uh_run>> On pour_point #1 of 1
INFO:rout>> Starting routing program for point: Point(outlet_58.3500_93.5500, lat:58.3500, lon:93.5500, y:167, x:125)
INFO:rout>> Input Latitude: 58.350000
INFO:rout>> Input Longitude: 93.550000
INFO:rout>> Global Basid ID: 35684
DEBUG:rout>> Grid cells in subset: 204402
ERROR:write>> Traceback (most recent call last):
ERROR:write>>   File "./lib/python/rvic-1.1.1-py3.6-linux-x86_64.egg/EGG-INFO/scripts/rvic", line 61, in <module>
ERROR:write>> main()
ERROR:write>>   File "./lib/python/rvic-1.1.1-py3.6-linux-x86_64.egg/EGG-INFO/scripts/rvic", line 43, in main
ERROR:write>> parameters(args.config_file, numofproc=args.numofproc)
ERROR:write>>   File "/projects/mas1261/wp3/RVIC/lib/python/rvic-1.1.1-py3.6-linux-x86_64.egg/rvic/parameters.py", line 90, in parameters
ERROR:write>> config_dict, directories)
ERROR:write>>   File "/projects/mas1261/wp3/RVIC/lib/python/rvic-1.1.1-py3.6-linux-x86_64.egg/rvic/parameters.py", line 454, in gen_uh_run
ERROR:write>> config_dict['ROUTING'])
ERROR:write>>   File "/projects/mas1261/wp3/RVIC/lib/python/rvic-1.1.1-py3.6-linux-x86_64.egg/rvic/core/make_uh.py", line 84, in rout
ERROR:write>> glons=basin['lon'])
ERROR:write>>   File "/projects/mas1261/wp3/RVIC/lib/python/rvic-1.1.1-py3.6-linux-x86_64.egg/rvic/core/utilities.py", line 36, in latlon2yx
ERROR:write>> if (plons.max() > 180):
ERROR:write>> AttributeError
ERROR:write>> :
ERROR:write>> 'float' object has no attribute 'max'

**Comment by solomonsg** [comment]
Hi, 

How did you solve this issue? I am getting the same error.

Thanks 
Solomon

**Comment by iacopoff** [comment]
Hi no I gave up, I am using this tool: https://github.com/nmizukami/mizuRoute
