### ISSUE TITLE
Output format time series

### ISSUE THREAD

**Issue by lizaclark** [UW-Hydro/RVIC#90]
It would be cool to have an option to output data with the coordinates (time, basin_id) instead of (time, lat, lon). Unless an application requires routing to virtually every grid cell, most users only want the time series at a series of points. The output files should also be smaller if an empty time series isn't saved for every other grid cell. I am willing to work on this in a couple of weeks from now if it seems reasonable.

**Comment by jhamman** [comment]
Oh, but there is such an option. From the `HISTORY` section in the documentation:

http://rvic.readthedocs.org/en/latest/user-guide/convolution/

> **RVICHIST_OUTTYPE**
>     - Description: History file output shape
>         - grid - shape is (time, y, x)
>         - array - shape is (time, outlets)
>     - Type: char
>     - Valid values: grid, array
